### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by atishp04** [stephenfin/pwclient#1]
Hi,
The following link for cloning didn't work for me.

git clone https://github.com/getpatchwork/pwclient

But I could clone it from 
git clone https://github.com/stephenfin/pwclient.git

However, I couldn't install it using
sudo python setup.py

atish@jedi-01:~/freedom-u-sdk/linux/pwclient$ sudo python setup.py 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

Am I missing something?

**Comment by saiprakash-ranjan** [comment]
Run as "sudo python setup.py install"

**Comment by atishp04** [comment]
It worked. Thanks.
