### ISSUE TITLE
Apply a patch series ?

### ISSUE THREAD

**Issue by atishp04** [stephenfin/pwclient#3]
Hi,
Is there a direct way to apply a complete patch series ?

I can pass individual patch ID as an arguments like below. But this is cumbersome for a series with large number patches.
pwclient get ID1 ID2

**Comment by stephenfin** [comment]
Sorry for the delay: I missed this.

I'd suggest you look at [`git-pw`](https://pypi.org/project/git-pw) which will allow you to do this. Note that this will require your patchwork server be version 2.0 or greater though (for series support).
